### ISSUE TITLE
Next release due date?

### ISSUE THREAD

**Issue by lakhvirss** [alpha-build/alpha-build#24]
Hi Cristian, great work as always on this powerful tool. 

Curious, the upgrade steps - does this require you to have pushed the latest release to PyPi? I see there have been some commits but pulling from PyPi with an install doesn't give me the latest changes.

Thanks

**Comment by cristianmatache** [comment]
Hi @lakhvirss, thank you!

Only the git-bash utils component had recent more changes. And that is already published to `pypi` https://pypi.org/project/alpha-build-git-bash-utils.

There was another commit for a simplified version of `alpha-build/core`, which offloads most formatters and static analysis tools to `pre-commit`
